% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Sep-2018 17:59:57
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('data_yes.mat');

attitude_rollradians = saveVarsMat.attitude_rollradians; % <9442x1 double> too many elements

attitude_yawradians = saveVarsMat.attitude_yawradians; % <9442x1 double> too many elements

time = saveVarsMat.time; % <9442x1 double> too many elements

clear saveVarsMat;
